# Generated by Django 3.0.6 on 2020-06-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bca', 'BCA'), ('mca', 'MCA')], max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
    ]
