# Generated by Django 3.0.6 on 2020-06-07 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+91xxxxxxxxxx'. Up to 12 digits allowed.", regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='photo',
            field=models.FileField(null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
