# Generated by Django 3.0.6 on 2020-06-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursename',
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bphrama', 'B.Pharma'), ('mpharma', 'M.Pharma'), ('bba', 'BBA'), ('mba', 'MBA'), ('bca', 'BCA'), ('mca', 'MCA'), ('polytechnic', 'Polytechnic')], default='btech', max_length=50, unique=True),
        ),
    ]
