# Generated by Django 3.0.6 on 2020-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200607_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=8, null=True),
        ),
    ]
