# Generated by Django 3.0.6 on 2020-06-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('bphrama', 'B.Pharma'), ('mpharma', 'M.Pharma'), ('biotech', 'Biotech'), ('bba', 'BBA'), ('mba', 'MBA'), ('bca', 'BCA'), ('mca', 'MCA'), ('polytechnic', 'Polytechnic')], default='btech', max_length=50, unique=True),
        ),
    ]
