# Generated by Django 3.0.6 on 2020-06-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20200603_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Branch'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Course'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='year',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
