# Generated by Django 3.0.6 on 2020-06-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200603_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[('1', 1), ('2', 2)], default=1, null=True),
        ),
    ]
