# Generated by Django 3.0.6 on 2020-06-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_glamember_preferred_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glamember',
            old_name='joined',
            new_name='joined_in',
        ),
        migrations.AddField(
            model_name='glamember',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Branch'),
        ),
        migrations.AddField(
            model_name='glamember',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Course'),
        ),
        migrations.AddField(
            model_name='glamember',
            name='rollno',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='glamember',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.City'),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.State'),
        ),
    ]
