# Generated by Django 3.0.6 on 2020-06-07 16:09

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200607_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='photo',
            field=models.FileField(null=True, upload_to=members.models.store_file_name),
        ),
    ]
