# Generated by Django 3.0.6 on 2020-06-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200603_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[('1', 1), ('2', 2)], null=True),
        ),
    ]
