# Generated by Django 3.0.6 on 2020-06-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20200603_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetails',
            options={'verbose_name': 'Course Detail', 'verbose_name_plural': 'Course Details'},
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.IntegerField(choices=[(1, '1 year'), (2, '2 years'), (3, '3 years'), (4, '4 years')], null=True),
        ),
    ]
