# Generated by Django 3.0.6 on 2020-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20200603_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLAMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
