# Generated by Django 3.0.6 on 2020-06-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_glamember_preferred_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
