# Generated by Django 3.0.6 on 2020-06-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_glamember_preferred_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='preferred_days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100, null=True),
        ),
    ]
