# Generated by Django 3.0.6 on 2020-06-08 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='preferred_days',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Day'),
        ),
    ]
