# Generated by Django 3.0.6 on 2020-06-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20200608_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glamember',
            name='preferred_days',
        ),
        migrations.AddField(
            model_name='glamember',
            name='preferred_days',
            field=models.ManyToManyField(null=True, to='members.Day'),
        ),
    ]
