# Generated by Django 3.0.6 on 2020-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20200608_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='preferred_days',
            field=models.ManyToManyField(to='members.Day'),
        ),
    ]
