# Generated by Django 3.0.6 on 2020-06-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20200608_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='glamember',
            options={'verbose_name': 'GLA Member', 'verbose_name_plural': 'GLA Members'},
        ),
    ]
