# Generated by Django 3.0.6 on 2020-06-08 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_auto_20200608_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +91xxxxxxxxxx', regex='^\\+?1?\\d{9,10}$')]),
        ),
    ]
