# Generated by Django 3.0.6 on 2020-06-09 08:40

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20200608_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('bphrama', 'B.Pharma'), ('mpharma', 'M.Pharma'), ('biotech', 'Biotech'), ('bba', 'BBA'), ('mba', 'MBA'), ('bca', 'BCA'), ('mca', 'MCA'), ('polytechnic', 'Polytechnic')], default='btech', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='photo',
            field=models.ImageField(null=True, upload_to=members.models.store_file_name),
        ),
    ]
