# Generated by Django 3.0.6 on 2020-06-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20200609_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
