# Generated by Django 3.0.6 on 2020-06-22 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20200621_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], help_text='select your gender', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='phone',
            field=models.CharField(blank=True, help_text='+91xxxxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +91xxxxxxxxxx', regex='^\\+?1?\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='glamember',
            name='year',
            field=models.IntegerField(choices=[('', ''), (1, 1), (2, 2), (3, 3), (4, 4)], help_text='select year', null=True),
        ),
    ]
