# Generated by Django 3.0.6 on 2020-06-22 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20200622_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='phone',
            field=models.CharField(blank=True, help_text='+91xxxxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +91xxxxxxxxxx', regex='^\\+?1?\\d{9,13}$')]),
        ),
    ]
