# Generated by Django 3.0.6 on 2020-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20200623_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glamember',
            name='joined_in',
            field=models.DateField(help_text='date of joining Udaaan', null=True),
        ),
    ]
