# Generated by Django 3.0.6 on 2020-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0021_auto_20200609_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now=True, null=True)),
                ('members', models.ManyToManyField(to='members.GLAMember')),
            ],
        ),
    ]
