# Generated by Django 3.0.6 on 2020-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummy',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
