# Generated by Django 3.0.6 on 2020-06-10 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200610_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dummy',
            old_name='date',
            new_name='datetime',
        ),
    ]
