# Generated by Django 3.0.6 on 2020-06-10 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20200609_1410'),
        ('attendance', '0003_auto_20200610_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Day'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='members',
            field=models.ManyToManyField(to='members.GLAMember'),
        ),
    ]
