# Generated by Django 3.0.6 on 2020-06-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20200620_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
