# Generated by Django 3.0.6 on 2020-06-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200620_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=10, null=True),
        ),
    ]
