# Generated by Django 3.0.6 on 2020-06-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200612_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
