# Generated by Django 3.0.6 on 2020-06-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='slug',
            field=models.SlugField(blank=True, default='some date', max_length=10, null=True),
        ),
    ]
