# Generated by Django 3.0.6 on 2020-06-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20200612_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='day',
        ),
    ]
