# Generated by Django 3.0.6 on 2020-06-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20200630_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='slug',
            field=models.SlugField(blank=True, default='some date', max_length=11, null=True),
        ),
    ]
