# Generated by Django 3.0.6 on 2020-06-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20200630_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='present',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
